name: pyos_group26
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0
  - anyio=4.10.0
  - backports.zstd=1.1.0
  - bcrypt=5.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - click=8.2.1
  - colorama=0.4.6
  - copier=9.11.0
  - cryptography=46.0.3
  - distlib=0.4.0
  - dunamai=1.25.0
  - eval-type-backport=0.2.2
  - expat=2.7.3
  - filelock=3.20.0
  - funcy=2.0
  - h11=0.16.0
  - hatch=1.16.2
  - hatchling=1.27.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperlink=21.0.0
  - idna=3.11
  - importlib_resources=6.5.2
  - invoke=2.2.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jinja2=3.1.6
  - jinja2-ansible-filters=1.3.2
  - keyring=25.7.0
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - more-itertools=10.8.0
  - ncurses=6.5
  - openssl=3.0.18
  - packaging=25.0
  - paramiko=4.0.0
  - pathspec=0.12.1
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - plumbum=1.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pynacl=1.6.0
  - pyproject_hooks=1.2.0
  - python=3.12.12
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - questionary=2.1.1
  - readline=8.3
  - rich=14.2.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.51.1
  - tk=8.6.15
  - tomli-w=1.2.0
  - tomlkit=0.13.3
  - trove-classifiers=2025.5.9.12
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - userpath=1.9.2
  - uv=0.9.22
  - virtualenv=20.28.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /Users/manikanthgoudgurujala/miniforge3/envs/pyos_group26
